### ISSUE TITLE
Breaking serialization

### ISSUE THREAD

**Issue by dyu** [openforis/collect#12]
https://github.com/openforis/collect/blob/5ef211c40f7727bcca53f803e9eefc525af269e8/collect-core/src/main/java/org/openforis/idm/model/Field.java#L23

Just noting here that using protostuff's [@Tag](http://www.protostuff.io/documentation/runtime-schema/) will avoid breakage in a cleaner way while keeping your related fields together (rather than appending all the time).

Cheers

**Comment by fefrain** [comment]
Thanks David,
That annotation has been added after we started to use Protostuff... so thanks for suggesting it! 
Anyway, do you think it's safe to migrate to the latest version of this library? 1.0.12 seems to be latest "legacy" version, right?
Thanks from all the Open Foris Team
