### ISSUE TITLE
Species table does not import legitimately hyphenated species, cultivars

### ISSUE THREAD

**Issue by thayeray** [openforis/collect#14]
I have 2 issues:
1) I am wondering if hyphens can be allowed into the species table scientific_name in varieties?
  For example Liatris scariosa var. novae-angliae <-- note the hyphen, this is the correct spelling.
https://www.plants.usda.gov/core/profile?symbol=LISCN2

2) I am wondering if it is possible to add 'cv.' for cultivar to the list of legitimate categories for the species table scientific_name? As far as I can tell only 'spp.', 'subsp.' and 'var.' are currently allowed
  Cultivar names need to allow for capital letters, numbers and spaces, probably there should be no quality control on cultivar names.

Thanks for your input on these requests. If you could at least point me to the correct areas of the code I can make my own edits.

-Thayer

**Comment by fefrain** [comment]
Dear Thayer,
the version 3.22.8 will support hyphen in the variety names and cultivar, but cultivar epithets must be placed in single quotes, e.g.: Chamaecyparis lawsoniana 'Aureomarginata'
Thanks,
Open Foris Team

**Comment by nanshany** [comment]
I tried to adjust plantations_brazil.cep (http://www.openforis.org/tools/collect-earth.html) to my application based on Open Foris Collect (Version: 3.24.20, the latest version). Then i tried to export the adjusted survey using Collect earth mode. But Export survey failed. And 'Error generating file: null' was appeared.
