### ISSUE TITLE
export error

### ISSUE THREAD

**Issue by nanshany** [openforis/collect#15]
I tried to adjust plantations_brazil.cep (http://www.openforis.org/tools/collect-earth.html) to my application based on Open Foris Collect (Version: 3.24.20, the latest version). Then i tried to export the adjusted survey using Collect earth mode. But Export survey failed. And 'Error generating file: null' was appeared.

**Comment by herrtunante** [comment]
Dear Nanshany,

Can you export it into any other format (Collect or Collect Backup)?
Can you send us the exceptions in the log file ( C:\OpenForis\Collect\logs\collect.log )

Thanks.

**Comment by nanshany** [comment]
Thanks for your response.
I can export it into Collect Desktop and Collect Mobile. Only Collect Earth failed.
[collect_server.log](https://github.com/openforis/collect/files/3187441/collect_server.log)

**Comment by nanshany** [comment]
Dear herrtunante,



I can export it into Collect Desktop and Collect Mobile. Only Collect Earth
failed.
collect_server.log
<https://github.com/openforis/collect/files/3187441/collect_server.log>



Thanks for your help in advance.

Look forward to your response at your earliest convenience.






[image: image.png]
[image: image.png]

[image: image.png]

[image: image.png]



------------------------------------------------------------------------------------

Nanshan You, PhD candidate

Institute of Geographic Sciences and Natural Resources Research (IGSNRR),

Chinese Academy of Sciences (CAS)

youns.18b@igsnrr.ac.cn / nanshany1993@outlook.com

**Comment by nanshany** [comment]
Excellent！ New version (3.24.22) solve the export (.cep) problems! Thanks for OF's efforts!
