### ISSUE TITLE
please how to  compile and run "collect"  project  (website and server)  like the installed version

### ISSUE THREAD

**Issue by ibouchoucha** [openforis/collect#29]
kindly, i would like to compile and run the "collect" project exactly like the installed version, (openforis-website and  control-panel) please show me how to compile and run , i'v tried via mvn command under 'collect' folder but didn't fully got it,  could you please give instructions to follow , it's  imperatively important to progress,   
thank you very much  in advance

**Comment by SteRiccio** [comment]
Dear user,
you should follow the instructions in the CONTRIBUTING.md file (https://github.com/openforis/collect/blob/master/CONTRIBUTING.md).
The main branch is "master", but it's not a stable one. You can try to build your own version starting from one of the latest tags (the latest one is collect-3.26.23).
To build the installers we use VMWare Installbuilder (a license is required to run it, but you can try to ask a license for open source projects for free).
Why do you need to build your own version of Collect? Do you want to apply some changes to the code? Can these changes be useful to other users? If so, why don't you open a pull request with these changes and we can try to merge them in our code?
Thanks,
Stefano
